name: probar text

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Hello World'
        run: echo 'Hello World!'
      - name: 'Dime la fecha'
        run: date
      - name: 'Muestra el contenido del directorio'
        run: ls -la
      - name: 'Muestra la versi贸n de Node.js'
        run: node --version
      - name: 'Muestra la versi贸n de npm'
        run: npm --version
      - name: 'Muestra la versi贸n de Python'
        run: python --version
      - name: 'Muestra la versi贸n de pip'
        run: pip --version
